#!/usr/bin/python

import alfred
import json
import subprocess
import sys
import urllib
import uuid


if __name__ == '__main__':
  '''
  Environment variables to be set by callers:

  Optional:
    - basedir: relative html paths will be resolved wrt this
               defaults to workflow dir

  Mandatory:
    - arg: the argument is passed to the script filter
  '''
  alfreditems = json.load(sys.stdin)

  cssfilepath = '/tmp/%s.css' % str(uuid.uuid4())
  with open(cssfilepath, 'w') as tmpfile: tmpfile.write(alfred.theme_css())

  bkgColor = alfred.theme()['window.color']
  bkgColorWithoutAlpha = bkgColor[:-2]
  subprocess.call([
    'open', '-g',
    'alfred-extra-pane://update?%s' % urllib.urlencode({
      'cssFile': cssfilepath,
      'bkgColor': bkgColorWithoutAlpha
    })
  ])

  print(json.dumps(alfreditems, indent=2))
  sys.stdout.flush()
